tasks:
  - init: npm i && clear

image:
  file: .gitpod.dockerfile
vscode:
  extensions:
    - auchenberg.vscode-browser-preview@0.6.7:znPd0J3N3vyCIJGzU1M4uA==
    - redlin.remove-tabs-on-save@1.2.1:oo8vGLFgpWicEzdLvlC/8g==
    - sasjs.sasjs-for-vscode@1.4.0:/GUqCe15740oweFTU5v3/A==